version: '3'

services:
  node-api:
    container_name: node_container
    build: .
    ports:
      - "5000:5000"
    restart: always
    networks:
      - mern-network
  mongo-db:
    container_name: mongo_container
    image: mongo
    networks:
      - mern-network
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db


volumes:
  mongodb-data:

networks:
  mern-network:
    driver: bridge